
version: '3.9'
services:
  checkmk-service:
    image: checkmk/check-mk-raw:2.1.0-latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - monitoring:/omd/sites
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ports:
      - 8084:5000
      - 8083:8000
    networks:
      - monitor-network
networks:
  monitor-network:
volumes:
  monitoring: {}
